### ISSUE TITLE
duration not defined

### ISSUE THREAD

**Issue by prashant-awasthi** [SeverinDK/moment-timer#9]
var timer = moment.duration(5, "seconds").timer({
                  ^

TypeError: Cannot read property 'duration' of undefined
    at Object.<anonymous> (C:\Users\SkullNull\Desktop\abcde\timer.js:2:19)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

**Comment by SeverinDK** [comment]
Looks like moment.js can't be found. Did you remember to include that?

**Comment by SeverinDK** [comment]
Closing this. I assume you solved the issue yourself.

**Comment by axaygadekar** [comment]
i am using node js
